### ISSUE TITLE
Can't go into Cache Management & Tax Rules after installation

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#72] opened 2016-09-23 12:37 UTC
Clean install today, got a similar error

`1 exception(s):
Exception #0 (Exception): Warning: Parameter 4 to Magento\Framework\Filter\Truncate::__construct() expected to be a reference, value given in /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

Exception #0 (Exception): Warning: Parameter 4 to Magento\Framework\Filter\Truncate::__construct() expected to be a reference, value given in /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
#0 /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Framework\App\ErrorHandler->handler()
#1 /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#2 /home/dev/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#3 /home/dev/public_html/vendor/magento/framework/Filter/AbstractFactory.php(90): Magento\Framework\ObjectManager\ObjectManager->create()
#4 /home/dev/public_html/vendor/magento/framework/Filter/FilterManager.php(87): Magento\Framework\Filter\AbstractFactory->createFilter()
#5 /home/dev/public_html/vendor/magento/framework/Filter/FilterManager.php(133): Magento\Framework\Filter\FilterManager->createFilterInstance()
#6 /home/dev/public_html/vendor/magento/module-backend/Block/Widget/Grid/Column/Renderer/Longtext.php(32): Magento\Framework\Filter\FilterManager->__call()
#7 /home/dev/public_html/vendor/magento/module-backend/Block/Widget/Grid/Column.php(276): Magento\Backend\Block\Widget\Grid\Column\Renderer\Longtext->render()
#8 /home/dev/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/column_set.phtml(113): Magento\Backend\Block\Widget\Grid\Column->getRowField()
#9 /home/dev/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#10 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#11 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#12 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#13 /home/dev/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /home/dev/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#15 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#17 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#18 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement()
#19 /home/dev/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#20 /home/dev/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#21 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#22 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#23 /home/dev/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#24 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#25 /home/dev/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#26 /home/dev/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#27 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#28 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#29 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#30 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement()
#31 /home/dev/public_html/vendor/magento/module-backend/Block/Widget/Grid/Container.php(118): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#32 /home/dev/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/container.phtml(13): Magento\Backend\Block\Widget\Grid\Container->getGridHtml()
#33 /home/dev/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#34 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#35 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#36 /home/dev/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#37 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#38 /home/dev/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#39 /home/dev/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#40 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#41 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#42 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#43 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#44 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#45 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#46 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#47 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#48 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#49 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#50 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#51 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#52 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#53 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#54 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#55 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#57 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#58 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#59 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#60 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#61 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#62 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#63 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#64 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#65 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#66 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#67 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#68 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#69 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#70 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#71 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#72 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#73 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#74 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#75 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#76 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#77 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#78 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#79 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#80 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#81 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#82 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#83 /home/dev/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement()
#84 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#85 /home/dev/public_html/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#86 /home/dev/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render()
#87 /home/dev/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult()
#88 /home/dev/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#89 /home/dev/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#90 /home/dev/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run()
#91 {main}`

During "config" 
[CredisException]
read error on connection

......................................................................

[RedisException]
read error on connection

**Comment by magenx** [comment] 2016-09-23 18:01
i think this is just a magento bug

**Comment by atrixtech** [comment] 2016-09-23 18:12
This is the same error I had when trying to go into cache management after a magento 2 install, the ones I listed on my page were errors directly from redis rather than what magento tells me.  I installed again without varnish or hhvm installed and also disabled redis to get it all working but it does work great after that.

I think this script is a boon and very good, but there's always room for improvement.  I was unable to find a solution to the redis thing and I'm not sure if hhvm or varnish were related to the cause.  You can easily disable redis though to see if it solves your issue.  copy and make a backup of your app/etc/env.php file.  Then edit it and remove the following lines (delete them):
```
  'cache' =>
  array (
    'frontend' =>
    array (
      'default' =>
      array (
        'backend' => 'Cm_Cache_Backend_Redis',
        'backend_options' =>
        array (
          'server' => '127.0.0.1',
          'port' => '6380',
          'persistent' => 'db1',
          'database' => '1',
          'force_standalone' => '0',
          'connect_retries' => '2',
          'read_timeout' => '10',
          'automatic_cleaning_factor' => '0',
          'compress_data' => '0',
          'compress_tags' => '0',
          'compress_threshold' => '20480',
          'compression_lib' => 'gzip',
        ),
      ),
      'page_cache' =>
      array (
        'backend' => 'Cm_Cache_Backend_Redis',
        'backend_options' =>
        array (
          'server' => '127.0.0.1',
          'port' => '6380',
          'persistent' => 'db2',
          'database' => '2',
          'force_standalone' => '0',
          'connect_retries' => '2',
          'read_timeout' => '10',
          'automatic_cleaning_factor' => '0',
          'compress_data' => '1',
          'compress_tags' => '1',
          'compress_threshold' => '20480',
          'compression_lib' => 'gzip',
        ),
      ),
    ),
  ),
```

This will make magento return to its default caching, which while not as powerful a cache system as redis, is working bug free.

**Comment by magenx** [comment] 2016-09-23 18:24
the legs are coming from magento code anyway
https://github.com/magento/magento2/issues/792

**Comment by magenx** [comment] 2016-09-24 12:32
hi this is fixed now,
magento 2 is not compatible with hhvm.
also redis cache settings updated.

**Closed** 2016-09-30 12:44 UTC
